blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ æäº¤ Side Project æƒ³æ³•
    url: https://github.com/codelove-tw/ideas/issues/new?template=idea.md
    about: ä½¿ç”¨æ¨™æº–æ¨¡æ¿æäº¤ä½ çš„æƒ³æ³•
